### PR TITLE
Reviewed lombok usage.

### PR DESCRIPTION
**Pull request by sschnabe**
- removed getter/setter
- use @Setter for parameter
- use @Data for models
- removed @SneakyThrows
- removed manual toString() methods

### CODE REVIEW

**Comment by nazarovkv** [comment]
Please add `@FieldDefaults(level = AccessLevel.PRIVATE)`

**Comment by sschnabe** [comment]
I was to lazy to add this annotation to all classes, i've added  `lombok.config` with:

```txt
config.stopBubbling = true

lombok.accessors.chain = true
lombok.fieldDefaults.defaultPrivate = true
```

Should be the same.

**Comment by nazarovkv** [comment]
> I was to lazy to add this annotation to all classes, i've added  `lombok.config` with:
> 
> 
> 
> ```txt
> 
> config.stopBubbling = true
> 
> 
> 
> lombok.accessors.chain = true
> 
> lombok.fieldDefaults.defaultPrivate = true
> 
> ```
> 
> 
> 
> Should be the same.

Now you can remove `private` modifier from field :-)

**Comment by sschnabe** [comment]
All `private` modifier on parameters or only for model classes?

**Review by rpahli — APPROVED** [review]

**Pull request merged**
