### PR TITLE
feat: create catalog of uploaded charts

### PR DESCRIPTION
**Pull request by kumadee**
- fixes https://github.com/kokuwaio/helm-maven-plugin/issues/327

### CODE REVIEW

**Comment by sschnabe** [comment]
This pr is unchanged since last week. Please notify me when i should review this pr. Thanks!

**Comment by kumadee** [comment]
> This pr is unchanged since last week. Please notify me when i should review this pr. Thanks!

Sure. I will let you know. Thanks.

**Comment by kumadee** [comment]
@sschnabe 
Please feel free to review now. Since, I am on vacation, there will be delay in fixing any review comments. Thanks.

**Comment by kumadee** [comment]
Can someone please review the PR? If you have any questions/comments already, please let me know.
It would be really helpful if the feature is available by the end of the month.

**Review by sschnabe — APPROVED** [review]

**Comment by sschnabe** [comment]
@kumadee  Thx, i'll release a new version next week after #338 is merged.

**Comment by sschnabe** [comment]
Released with [6.12.0](https://github.com/kokuwaio/helm-maven-plugin/releases/tag/6.12.0)

**Pull request merged**
