### PR TITLE
add capability to push to OCI registry

### PR DESCRIPTION
**Pull request by mlkmhd**
pushing helm chart to OCI registry (like `docker registry`) added by default from `helm >= v3.8.0` 
as a feature request needed here #120 , I added the ability to push helm chart to OCI registries.

### CODE REVIEW

**Comment by mlkmhd** [comment]
@sschnabe 
I didnot used the `getLog()` method in `login` method. but in the `callCli` I turned on the `verbose` log, so the password shows in terminal. do you mean I disable the `verbose` log?
https://github.com/mlkmhd/helm-maven-plugin/blob/main/src/main/java/io/kokuwa/maven/helm/PushMojo.java#L53

I think I have to change the command to read password from `stdin` instead of directly password in command line. the helm cli has a `--password-stdin` argument to hide password in command line

**Review by sschnabe — APPROVED** [review]
lgtm

**Comment by nazarovkv** [comment]
I guess it worth it to add check on helm version, since pushing to OCI registry requires helm >= 3.8.0.

**Comment by mlkmhd** [comment]
@nazarovkv 
thanks for your feedback. I added checking helm version in this line:
https://github.com/kokuwaio/helm-maven-plugin/pull/169/commits/1cde7e6e5e1ae9f99dcd09c40a22a0d1eb01d540#diff-a945af461a97e317f91a7c2ba98769c2e36c0c4fc017ee888e029b029cb88e3fR49

**Review by nazarovkv — APPROVED** [review]

**Comment by mlkmhd** [comment]
@nazarovkv 
thanks 🙏

**Comment by mlkmhd** [comment]
how can I get the `helm version` command output? it's not confident to take the helm version from `<helmVersion>3.2.0</helmVersion>` tag, because local helm binary (found in `PATH`) may differ from specified version 🤔
@nazarovkv 
@sschnabe

**Comment by sschnabe** [comment]
@mlkmhd right now there is no way, i've created #172

**Comment by mlkmhd** [comment]
@sschnabe thanks 🙏🏻
when do you release a new version to maven repository?

**Comment by sschnabe** [comment]
l will release 6.1.0 after #168 and #173 were merged. I think this will be tomorrow.

**Comment by mlkmhd** [comment]
@sschnabe thanks 🙏

**Comment by jmabecassis** [comment]
Hi Everyone! It's great to see the plugin now supports OCI. 
I do have a question however regarding the repository type to use for the plugin - We currently use Harbor in our company but the only options i see in the documentation are:
- ARTIFACTORY
- NEXUS
- CHARTMUSEUM

It seems to fail for both ARTIFACTORY and NEXUS so far... 
Please let me know if publishing to Harbor/Azure ACR are not supported here.

Thanks in advance

**Comment by mlkmhd** [comment]
@jmabecassis 
you can push to Azure ACR with OCI protocol but I'm not sure about Harbor. the OCI is the docker built-in protocol for pushing docker images. you can see this document for pushing helm chart to Azure ACR using OCI:
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos

**Comment by jmabecassis** [comment]
Thanks a lot for your reply but, Azure aside, what should you set the <type> to if I wanted to attempt a deployment of my OCI compliant chart to harbor with the plugin?

                                               <uploadRepoStable>
							<name>stable-repo</name>
							**<type>XXXXXXXX</type>**
							<url>${helm.registry}</url>
							<username>${helm.registry.username}</username>
							<password>${helm.registry.password}</password>
						</uploadRepoStable>

**Pull request merged**
